### ISSUE TITLE
[Bug] Formatting `property_value` field in `stg_klaviyo__event` model

### ISSUE THREAD

**Issue by vnguyen12** [fivetran/dbt_klaviyo_source#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The field `property_value` does not enforce float type and may contain non numerical characters from source, for example `$1,234.56`

### Relevant error log or model output

```shell
19:18:10  Completed with 1 error and 0 warnings:
19:18:10
19:18:10    Database Error in model stg_klaviyo__event (models/stg_klaviyo__event.sql)
  100038 (22018): Numeric value '$1,258.54' is not recognized
  compiled Code at target/run/klaviyo_source/models/stg_klaviyo__event.sql
```
```


### Expected behavior

1. `stg_klaviyo__event` should format `property_value` so the model can be built correctly

### dbt Project configurations

```
vars:
  shopify_database: <MY_DATABASE>
  shopify_schema: shopify
  shopify_using_fulfillment_event: true
  shopify_timezone: "America/Los_Angeles"
  shopify_source:
    has_defined_sources: true

  klaviyo_database: <MY_DATABASE>
  klaviyo_schema: klaviyo

  recharge_database: <MY_DATABASE>
  recharge_schema: recharge_ft
```

### Package versions

```
packages:
  - package: fivetran/shopify_holistic_reporting
    version: [">=0.5.0", "<0.6.0"]
  - package: fivetran/recharge
    version: [">=0.1.0", "<0.2.0"]
  - package: dbt-labs/codegen
    version: 0.12.1
  - package: narratorai/activity_schema
    version: 0.1.0

```

### What database are you using dbt with?

snowflake

### dbt Version

```
dbt --version
Core:
  - installed: 1.7.7
  - latest:    1.7.11 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.7.3 - Up to date!
```

### Additional Context

_No response_

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-avinash** [comment]
Hi @vnguyen12, thanks for bringing this to our attention, and the errors you are seeing in compilation! And also thanks for opening a PR here.

We are trying to reproduce the error on our end to complete scoping and potentially merge your PR. We haven't been able to see the error occur yet, although I do believe your `regex_replace` is needed for aggregations to occur properly. I had a few questions about the `property_value` field in your data.

- Are all the values in `property_value` all strings, or is it a mix of different types? 
- Are there any null values, or are they expressed as empty strings? Or are there examples of both?
- Are there different numeric types in the data? Integers, floats, etc.?
- Are you doing any unioning of different schemas? If so, I'm curious if `property_value` has the same data type in both schemas. 
- Do you think a `cast regexp_replace(property_value, '[^0-9.]*' ) as {{dbt_type.numeric()}}` is also needed in your PR, to ensure everything is in the same format?

Let me know your findings! I think we're close to getting this PR ready for review, but just want to ensure thoroughness so we patch this properly.

**Comment by vnguyen12** [comment]
@fivetran-avinash Thanks for getting back to me. To answer your questions...
1. The `property_value` field in my warehouse is of type `varchar` (aka strings)
2. Some of the rows do contain null `property_value` 
3. The column contains only string-liked values that looks like a float xx.xx or currency string $x,xxx.xx
4. I'm not doing any manual joins on my end. The models from the fivetran-dbt klaviyo package are all that I'm using
5. Yes, I think type-casting here would be good too to ensure that `property_value` is of the right type before being used downstream

**Comment by fivetran-avinash** [comment]
Thanks @vnguyen12 for all the helpful feedback! I'm in the midst of testing your changes now and trying to ensure that the logic will work for your case. I'll be in touch shortly.

**Comment by fivetran-avinash** [comment]
Hi @vnguyen12 ! We've been able to reproduce a version of your error and confirmed that your changes work. We are planning to bring this issue into our coming sprint next week and will hopefully have a branch ready for you to test our code (we still need to ensure cross-database compatibility).

**Comment by vnguyen12** [comment]
Thanks @fivetran-avinash, any update on this PR?

**Comment by vnguyen12** [comment]
@fivetran-avinash That sounds great! Thanks for the update!

**Comment by fivetran-avinash** [comment]
Hi @vnguyen12 ! Thanks for your patience, we should be on the verge of resolving your issue.

[We have a PR out](https://github.com/fivetran/dbt_klaviyo_source/pull/22) for this fix. We have [merged your PR](https://github.com/fivetran/dbt_klaviyo_source/pull/21) into this branch before release so you are properly credited as well. 

If you are to change your `packages.yml` to

```
packages:
  - git: https://github.com/fivetran/dbt_klaviyo_source.git
    revision: bugfix/property-value-as-numeric
    warn-unpinned: false 
```

you should be able to test and see if the new changes work! 

Let me know if you have any questions.

**Comment by fivetran-avinash** [comment]
Hi @vnguyen12 , these [changes are now live in our package in our latest release](https://hub.getdbt.com/fivetran/klaviyo_source/latest/). Let us know if you encounter any issues with this new release, and always reach out to us with any additional questions or issues you have.

Cheers and happy modeling!
