### ISSUE TITLE
QUESTION - Is there a possibility to target multiple datasets with this package?

### ISSUE THREAD

**Issue by pawelngei** [fivetran/dbt_klaviyo_source#7]
**Are you a Fivetran customer?** 
Pawel Ngei, Fullstack Developer / Data Engineer from Pattern Brands

**Your Question**
We would like to use `dbt_klaviyo` and `dbt_klaviyo_source` with data multiple instances of Klaviyo imported via Fivetran, each having its own schema in our database. Is there a way to configure this plugin to either:

- Feed it the data from multiple datasets, which could later be merged by us in another model?
- Instead of targeting a raw dataset, have it target a series of already-merged models created by us?

I'm fairly new to DBT and while I can see how I could _rewrite_ the plugin to do exactly that for us, I'm interested in whether we can still use it as a plug-and-play plugin within our architecture.

**Please indicate the level of urgency and business impact of this request** 
We cannot proceed with our Fivetran + Klaviyo data analysis without this feature. Rewriting it locally could make further maintenance much harder.

**Comment by fivetran-jamie** [comment]
just pushed this fix out in v0.3.0!
